title: Trevor Dodson
description: > # this means to ignore newlines until "baseurl:"
  If you find yourself writing essentially the same line of code three times, write a function. If you have to expain something three times write an article. The goal of this site is to democratize knowledge.
permalink: ':title/'
baseurl: "https://tjdodson.github.io" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: Trevor Dodson # add your name
author-img: HeadShots/portfolio_profile.png # add your photo
about-author: > # add description
  I am passionate about making data accessible to all through intelligent data architecture and engineering, but it is of little interest to do so unless I can also free the capacity of analysts and data scientists by automating the generation and implementation of business insights.

social-twitter: TrevorDodson7 # add your Twitter handle
social-facebook: trevor.dodson.5 # add your Facebook handle
social-github: tjdodson # add your Github handle
social-linkedin: trevor-dodson # add your Linkedin handle
social-email: trevorjoedodson@gmail.com # add your Email address

# Disqus
discus-identifier: # add your discus identifier

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
